### PR TITLE
Make changes to introduce Smaclite compatiblity

### PR DESCRIPTION
**Pull request by micadam**
I would appreciate if someone could check out the `smaclite` branch and test that it doesn't break anything. I did some minimal testing and it seems fine, but I don't use ePyMARL on a daily basis.

List of changes:
* handle the cases where the returns and the "done"s are not lists
* fix yaml complaining about implicit yaml loader definition
* add a parameter to enable rendering the environment
* add a way to render and save replays from parallel-run environments
* remove duplicate definitions of methods from `gymma`
* pass kwargs from `gymma` to the underlying environment
* trim trailing whitespace here and there

### CODE REVIEW

**Comment by semitable** [comment]
Thanks @micadam 
@papoudakis @LukasSchaefer How do we want to handle this?

I briefly went through the commits and it looks okay -- but I didn't really check thoroughly if anything is broken

**Comment by papoudakis** [comment]
I believe that at its current state we cannot merge  this pull request. There are changes in the algorithm files for no reason. And all of them are in a single commit. I would also recommend to create a different wrapper for the smaclite rather than modifying the existing one.

**Comment by micadam** [comment]
Just a note that there are no changes to the algorithm config files in the resulting changeset, all of them have been reverted and will be completely invisible if we squash the commits. The decision about having a separate wrapper is not mine to make, I suppose.

**Comment by semitable** [comment]
@papoudakis I am confused; I don't see any changes in the config files (except a render: False) in the default.yaml. I am looking at the "Files Changed" tab.

**Comment by semitable** [comment]
@papoudakis 
Actually, I realised that there is a config that reverts the "Prepare hyperparameters for full training suite". Maybe that's what you were looking at? I don't think any of the changes there apply for this PR: @micadam if you can confirm

**Comment by semitable** [comment]
My only concern is the deletion of some functions in the envs/__init__.py file. For example get_obs_agent and get_obs_size, or even the state. Maybe a separate class specifically for smaclite would be safer?

**Comment by micadam** [comment]
@semitable the deleted functions are exact duplicates of implementations directly above.
* `get_obs_agent` has identical implementations in lines [118-120](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L118-L120), and in lines [133-135](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L133-L135).
* `get_obs_size` has idential implementations in lines [122-124](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L122-L124) and in lines [137-139](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L137-L139)
* `get_state` has identical implementations in lines [126-127](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L126-L127) and in lines [141-142](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L141-L142)
* `get_state_size` has identical implementations in lines [129-131](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L129-L131) and [144-146](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L144-L146) 

The only methods with any actual changes in that class are `step` (support non-list rewards and dones), `get_state` (support child env's state), `get_state_size` (support child env's state size), and `get_avail_actions` (support child env's avail actions).

**Comment by semitable** [comment]
I don't think I can spot anything wrong with the PR. It even fixes some deprecations issues we had. If @papoudakis has any other concerns we can discuss

**Comment by rfali** [comment]
@semitable @papoudakis I think the epymarl ReadMe should reflect that it supports SMAC_Lite (as it does with LBF, RWARE etc.) I had come across SMAC_Lite but wasn't sure if epymarl supported it natively, or if there was a fork that supported it. After coming across this PR, I would believe that epymarl supports SMAC_Lite out of the box.

**Pull request merged**
